apiVersion: v1
kind: Service
metadata:
  name: streampets-backend-service
  namespace: streampets
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: streampets-backend
